//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppSastiServices.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SastaServicesDBEntities : DbContext
    {
        public SastaServicesDBEntities()
            : base("name=SastaServicesDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<STPBanner> STPBanners { get; set; }
        public virtual DbSet<STPBannerOffer> STPBannerOffers { get; set; }
        public virtual DbSet<STPConInspection> STPConInspections { get; set; }
        public virtual DbSet<STPContract_StpContUnitOptions> STPContract_StpContUnitOptions { get; set; }
        public virtual DbSet<STPContract> STPContracts { get; set; }
        public virtual DbSet<STPContractType> STPContractTypes { get; set; }
        public virtual DbSet<STPConType_STPServiceType> STPConType_STPServiceType { get; set; }
        public virtual DbSet<STPConUnitOption> STPConUnitOptions { get; set; }
        public virtual DbSet<STPCustomerSupport> STPCustomerSupports { get; set; }
        public virtual DbSet<STPMonth> STPMonths { get; set; }
        public virtual DbSet<STPNotification> STPNotifications { get; set; }
        public virtual DbSet<STPPrefferedTime> STPPrefferedTimes { get; set; }
        public virtual DbSet<STPProductBrand> STPProductBrands { get; set; }
        public virtual DbSet<STPProductList> STPProductLists { get; set; }
        public virtual DbSet<STPProductType> STPProductTypes { get; set; }
        public virtual DbSet<STPQuickCall> STPQuickCalls { get; set; }
        public virtual DbSet<StpRole> StpRoles { get; set; }
        public virtual DbSet<STPRolesCategory> STPRolesCategories { get; set; }
        public virtual DbSet<STPServiceProductItem> STPServiceProductItems { get; set; }
        public virtual DbSet<STPService> STPServices { get; set; }
        public virtual DbSet<STPServicesFuelType> STPServicesFuelTypes { get; set; }
        public virtual DbSet<STPServicesUnitType> STPServicesUnitTypes { get; set; }
        public virtual DbSet<STPServiceType> STPServiceTypes { get; set; }
        public virtual DbSet<STPStatu> STPStatus { get; set; }
        public virtual DbSet<STPStatusType> STPStatusTypes { get; set; }
        public virtual DbSet<StpUser> StpUsers { get; set; }
        public virtual DbSet<TRNCustomerOrder> TRNCustomerOrders { get; set; }
        public virtual DbSet<TRNCustomerOrders_STPProductItems> TRNCustomerOrders_STPProductItems { get; set; }
        public virtual DbSet<TRNCustomerOrders_STPServices> TRNCustomerOrders_STPServices { get; set; }
        public virtual DbSet<TRNInvoice> TRNInvoices { get; set; }
        public virtual DbSet<TRNSubscription> TRNSubscriptions { get; set; }
    }
}
