
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebAppSastiServices.Models.DB
{

using System;
    using System.Collections.Generic;
    
public partial class STPCustomerSupport
{

    public int ID { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public string Subject { get; set; }

    public string ContactNo { get; set; }

    public string Message { get; set; }

    public string RequestNumber { get; set; }

}

}
