//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppSastiServices.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class STPContract_StpContUnitOptions
    {
        public int ID { get; set; }
        public int STPContractID { get; set; }
        public int STPConUnitOptionsID { get; set; }
        public int QTY { get; set; }
        public decimal Price { get; set; }
    
        public virtual STPContract STPContract { get; set; }
        public virtual STPConUnitOption STPConUnitOption { get; set; }
    }
}
