//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppSastiServices.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class STPNotification
    {
        public int ID { get; set; }
        public string Message { get; set; }
        public bool Is_Notify { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
