//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppSastiServices.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRNCustomerOrders_STPProductItems
    {
        public int ID { get; set; }
        public int TRNCustomerOrderID { get; set; }
        public int STPProductItemsID { get; set; }
        public Nullable<int> QTY { get; set; }
    
        public virtual TRNCustomerOrder TRNCustomerOrder { get; set; }
        public virtual STPServiceProductItem STPServiceProductItem { get; set; }
    }
}
