//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppSastiServices.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRNCustomerOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRNCustomerOrder()
        {
            this.TRNCustomerOrders_STPProductItems = new HashSet<TRNCustomerOrders_STPProductItems>();
            this.TRNCustomerOrders_STPServices = new HashSet<TRNCustomerOrders_STPServices>();
            this.TRNInvoices = new HashSet<TRNInvoice>();
        }
    
        public int OrderId { get; set; }
        public string CustomerName { get; set; }
        public string Email { get; set; }
        public string Contact { get; set; }
        public string Address { get; set; }
        public string OrderDescription { get; set; }
        public System.DateTime preferredDate { get; set; }
        public int preferredTimeID { get; set; }
        public int ServiceTypeId { get; set; }
        public int FuelTypeId { get; set; }
        public int UnitTypeId { get; set; }
        public int OrderStatusId { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
    
        public virtual STPPrefferedTime STPPrefferedTime { get; set; }
        public virtual STPServicesFuelType STPServicesFuelType { get; set; }
        public virtual STPServicesUnitType STPServicesUnitType { get; set; }
        public virtual STPServiceType STPServiceType { get; set; }
        public virtual STPStatu STPStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRNCustomerOrders_STPProductItems> TRNCustomerOrders_STPProductItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRNCustomerOrders_STPServices> TRNCustomerOrders_STPServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRNInvoice> TRNInvoices { get; set; }
    }
}
