//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppSastiServices.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRNInvoice
    {
        public int ID { get; set; }
        public int STPOrdersID { get; set; }
        public decimal ProductItemCharges { get; set; }
        public decimal ServiceCharges { get; set; }
        public decimal PlatformCharges { get; set; }
        public decimal TotalAmount { get; set; }
        public Nullable<decimal> GSTTax { get; set; }
        public Nullable<decimal> SpecialDiscount { get; set; }
    
        public virtual TRNCustomerOrder TRNCustomerOrder { get; set; }
    }
}
